---
title: "Lab 03 - Nobel laureates"
author: "Kyle Knaut"
date: "January 15th, 2024"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
```

## Exercises

### Exercise 1

```{r exploring-dataset-observations}
# there are 935 observations in this dataset, which are represented by rows. These rows
# contain observations of 26 different variables which can be seen below
# the variables will be represented by collums in the dataframe

glimpse(nobel)

```

### Exercise 2

```{r filtering-data}
#nobel_living4 = filter(nobel, gender!="org" & country!='NA')

nobel_living <- nobel %>% 
  filter(gender != "org") %>%
  filter(!is.na(country)) %>% #filter(country != 'NA') %>%
  filter(is.na(died_date))

                      
#Watched a video on the channel Mike Jonas Econometricts to try to figure this out, it kinda 
#helped but the biggest problem is still filtering out dead winners. When I try to filter for 
#died_date = NA, no matter whether I use quotations, single quotes, or any attempt to use the NA 
#value, it always leaves me with zero observations, which tells me it doesnt like the syntax that
#Im trying to use to say there is no value for died_date
  
#glimpse(nobel_living4)
```


### Exercise 3

```{r USA-test}
nobel_living <- nobel_living %>%
  mutate(country_us = if_else(country == "USA", "USA", "Other"))

```

### Exercise 4

```{r categorization}
nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))

#This is a new dataframe that is limited to
#observations of Physics, Medicine, Chemistry
# and Economics
```

### Exercise 5
```{r bar-plot}
ggplot(nobel_living_science, aes(x = country_us, fill = country_us)) + geom_bar() + coord_flip() + labs( x = "Nobel Prize Winners", y = "Country", title = "Country of Nobel Prize Winners by category") + facet_wrap(~ category)

#Faceted bar graphs of where each nobel prize winner is from
```
...

### Exercise 6
```{r born-in-the-USA-plus-vis}
nobel_living_science <- nobel_living %>%
  mutate(born_country_us = if_else(born_country == "USA", "USA", "Other")) 

#ggplot(nobel_living_science, aes(x = born_country_us, fill = born_country_us)) + geom_bar() + coord_flip() + labs( x = "Nobel Prize Winners", y = "Country of Birth", title = "Birth Country of Nobel Prize Winners by category", fill = "Country of Birth") + facet_wrap(~ category)

ggplot(nobel_living_science, aes(x = country_us, fill = born_country_us)) + geom_bar() + coord_flip() + labs( x = "Nobel Prize Winners", y = "Country", title = "Country of Nobel Prize Winners by category", fill = "Country of Birth") + facet_wrap(~ category)
```

...

### Exercise 7
```{r freq}

```